# Boolean Mask Arrays

In [25]:
import numpy as np

In [26]:
my_vector = np.array([12,1,-12,20,1])
my_vector

array([ 12,   1, -12,  20,   1])

In [27]:
my_mod_vector = 0 == (my_vector % 2)
my_mod_vector

array([ True, False,  True,  True, False], dtype=bool)

In [28]:
my_mod_vector = 1 == (my_vector % 2)
my_mod_vector

array([False,  True, False, False,  True], dtype=bool)

In [29]:
sub_vector = my_vector[my_mod_vector]
sub_vector

array([1, 1])

In [30]:
sub_vector[sub_vector > 0]

array([1, 1])

# Numpy logical operators

In [31]:
mod_test = 0 == (my_vector % 2)

In [32]:
positive_test = my_vector > 0

In [33]:
positive_test

array([ True,  True, False,  True,  True], dtype=bool)

In [34]:
combined_mask = np.logical_and(mod_test,positive_test)
combined_mask

array([ True, False, False,  True, False], dtype=bool)

# Broadcasting

In [35]:
my_3d = np.arange(70)
my_3d.shape = (2,7,5)
my_3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [36]:
# shape
my_3d.shape

(2, 7, 5)

In [37]:
# no of dimension
my_3d.ndim

3

In [38]:
# size
my_3d.size

70

In [39]:
# data type for each element
my_3d.dtype

dtype('int32')

In [40]:
5 * my_3d - 2 

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [41]:
left_mat = np.arange(6).reshape((2,3))
right_mat = np.arange(15).reshape((3,5))

In [42]:
#np.inner(left_mat,right_mat)

In [43]:
np.dot(left_mat,right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

### Operations along axes

In [44]:
my_3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [45]:
my_3d.shape

(2, 7, 5)

In [46]:
my_3d.sum()

2415

In [47]:
my_3d.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [48]:
my_3d.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [49]:
my_3d.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

### Broadcasting Rules

In [50]:
my_2d = np.ones(35,dtype='int_').reshape((7,5))*3
my_2d

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [51]:
my_random = np.random.random((7,5))
my_random

array([[ 0.24671094,  0.54309821,  0.07040719,  0.05285805,  0.36087939],
       [ 0.3908499 ,  0.32017555,  0.40512837,  0.28274367,  0.32520338],
       [ 0.24328723,  0.62147912,  0.15973123,  0.77506427,  0.4050192 ],
       [ 0.24465638,  0.43986355,  0.65044181,  0.91315271,  0.88923646],
       [ 0.72785284,  0.50746127,  0.83954874,  0.7985586 ,  0.42568911],
       [ 0.80193666,  0.87017967,  0.72613139,  0.02490194,  0.24997609],
       [ 0.64601585,  0.7773943 ,  0.10677303,  0.34350278,  0.43946093]])

In [52]:
np.set_printoptions(precision=4)
my_3d * my_random

array([[[  0.    ,   0.5431,   0.1408,   0.1586,   1.4435],
        [  1.9542,   1.9211,   2.8359,   2.2619,   2.9268],
        [  2.4329,   6.8363,   1.9168,  10.0758,   5.6703],
        [  3.6698,   7.0378,  11.0575,  16.4367,  16.8955],
        [ 14.5571,  10.6567,  18.4701,  18.3668,  10.2165],
        [ 20.0484,  22.6247,  19.6055,   0.6973,   7.2493],
        [ 19.3805,  24.0992,   3.4167,  11.3356,  14.9417]],

       [[  8.6349,  19.5515,   2.6051,   2.0086,  14.0743],
        [ 15.634 ,  13.1272,  17.0154,  12.158 ,  14.3089],
        [ 10.9479,  28.588 ,   7.5074,  37.2031,  19.8459],
        [ 12.2328,  22.433 ,  33.823 ,  48.3971,  48.0188],
        [ 40.0319,  28.4178,  47.8543,  46.3164,  25.1157],
        [ 48.1162,  53.081 ,  45.0201,   1.5688,  15.9985],
        [ 41.991 ,  51.308 ,   7.1538,  23.3582,  30.3228]]])

In [53]:
my_vector = np.arange(5)*7
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [54]:
my_3d / my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [55]:
my_3d % my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]], dtype=int32)

In [63]:
test = np.arange(16).reshape(4,4)
#test.shape = (4,4)
test

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
test.shape = (2,8)
test

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [69]:
test.reshape((8,2))
test

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])