# Intrinsic numpy array creation using NumPy's methods

In [1]:
import numpy as np

In [2]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [3]:
np.arange(10,19)

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [5]:
np.arange(10,19) - 10 + 1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
len(np.arange(10,19))

9

In [8]:
(np.arange(10,19)).size

9

In [9]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [10]:
np.arange(20,step= 5)

array([ 0,  5, 10, 15])

In [11]:
np.arange(0,25,step = 5)

array([ 0,  5, 10, 15, 20])