# linspace(),zeros(),ones() and numpy datatypes

In [2]:
import numpy as np

In [3]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [4]:
mylin = np.linspace(5,15,9,retstep = True)

In [5]:
mylin

(array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ]),
 1.25)

# zeros()

In [6]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [7]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [8]:
np.zeros((5,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [9]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
np.zeros((5,4,3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [11]:
np.linspace(1,5,7,dtype = 'float')

array([ 1.        ,  1.66666667,  2.33333333,  3.        ,  3.66666667,
        4.33333333,  5.        ])

In [19]:
a = (np.ones((4))*8).reshape(2,2)
print(a)
a.reshape(4,1)

[[ 8.  8.]
 [ 8.  8.]]


array([[ 8.],
       [ 8.],
       [ 8.],
       [ 8.]])