# Magic Squares

In [3]:
import numpy as np
from numpy.linalg import inv

In [28]:
from IPython.display import display, Math, Latex
display(Math(r'1*X^2+0*X^1-4 = 0'))
display(Math(r'X^2-4 = 0'))
display(Math(r'X = \sqrt{4}'))
display(Math(r'X = \pm4'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [5]:
equation = [1,0,-4]
# equation is 1*X^2 + 0*X^1 - 4*X^0 = 0
# x^2 - 4 = 0
# x^2 = 4 is -2 and +2
#roots of X^2 = 4 is -2 and +2
np.roots(equation)

array([ 2., -2.])

# Adjacent Matrix

In [10]:
def Adjacent_Matrix(dimensions):
    matrix = np.ones((dimensions, dimensions), dtype=np.int64)
    for i in range(dimensions):
                for j in range(dimensions):
                    if ((i + j) > (dimensions - 2)):
                        matrix[i,j] = 1
                    else:
                        matrix[i,j] = -1
    return matrix

In [11]:
am = Adjacent_Matrix(7)

In [12]:
am

array([[-1, -1, -1, -1, -1, -1,  1],
       [-1, -1, -1, -1, -1,  1,  1],
       [-1, -1, -1, -1,  1,  1,  1],
       [-1, -1, -1,  1,  1,  1,  1],
       [-1, -1,  1,  1,  1,  1,  1],
       [-1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1]], dtype=int64)

In [13]:
aam = am.T

In [14]:
aam

array([[-1, -1, -1, -1, -1, -1,  1],
       [-1, -1, -1, -1, -1,  1,  1],
       [-1, -1, -1, -1,  1,  1,  1],
       [-1, -1, -1,  1,  1,  1,  1],
       [-1, -1,  1,  1,  1,  1,  1],
       [-1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1]], dtype=int64)

In [21]:
inv(aam)

array([[ 0. ,  0. ,  0. ,  0. ,  0. , -0.5,  0.5],
       [ 0. ,  0. ,  0. ,  0. , -0.5,  0.5,  0. ],
       [ 0. ,  0. ,  0. , -0.5,  0.5,  0. ,  0. ],
       [ 0. ,  0. , -0.5,  0.5,  0. ,  0. ,  0. ],
       [ 0. , -0.5,  0.5,  0. ,  0. ,  0. ,  0. ],
       [-0.5,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5]])