# Single Element

In [4]:
import numpy as np

In [5]:
my_vector = np.array([1,2,-12,0,122])

In [6]:
my_vector[1]

2

In [7]:
my_vector/3

array([  0.33333333,   0.66666667,  -4.        ,   0.        ,  40.66666667])

In [8]:
my_vector.size

5

# Two Dimensional

In [9]:
num = np.arange(35)
num.shape = (5,7)
num

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [10]:
num[2]

array([14, 15, 16, 17, 18, 19, 20])

In [14]:
num[-1]

array([28, 29, 30, 31, 32, 33, 34])

In [10]:
num[4,1]

29

In [11]:
row =  0 
col = 1
num[row,col]

1

In [12]:
num[1][3]

10

# Three Dimensional

In [13]:
num_30 = np.arange(70)
num_30.shape = (2,5,7) 
num_30

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62],
        [63, 64, 65, 66, 67, 68, 69]]])

In [14]:
num_30[1,2]

array([49, 50, 51, 52, 53, 54, 55])

In [15]:
num_30[1,1,1]

43

In [16]:
num_30[0,0]

array([0, 1, 2, 3, 4, 5, 6])