In [1]:
import numpy as np

In [2]:
# truncated binomial: returns (x+1)**3 - (x)**3
def truncated_binomial(x):
    return (x+1)**3 - (x)**3

In [3]:
np.testing.assert_equal (truncated_binomial(4), 61)

In [4]:
np.testing.assert_equal (truncated_binomial(4), 65)

AssertionError: 
Items are not equal:
 ACTUAL: 61
 DESIRED: 65

In [5]:
my_numpy_function = np.frompyfunc(truncated_binomial, 1, 1)
my_numpy_function

<ufunc '? (vectorized)'>

In [6]:
test_array = np.arange(10)
test_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_numpy_function(test_array)

array([1, 7, 19, 37, 61, 91, 127, 169, 217, 271], dtype=object)

In [8]:
big_test_array = np.outer(test_array,test_array)
big_test_array

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [9]:
my_numpy_function(big_test_array)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 7, 19, 37, 61, 91, 127, 169, 217, 271],
       [1, 19, 61, 127, 217, 331, 469, 631, 817, 1027],
       [1, 37, 127, 271, 469, 721, 1027, 1387, 1801, 2269],
       [1, 61, 217, 469, 817, 1261, 1801, 2437, 3169, 3997],
       [1, 91, 331, 721, 1261, 1951, 2791, 3781, 4921, 6211],
       [1, 127, 469, 1027, 1801, 2791, 3997, 5419, 7057, 8911],
       [1, 169, 631, 1387, 2437, 3781, 5419, 7351, 9577, 12097],
       [1, 217, 817, 1801, 3169, 4921, 7057, 9577, 12481, 15769],
       [1, 271, 1027, 2269, 3997, 6211, 8911, 12097, 15769, 19927]], dtype=object)

<h1>Pythagorean Triangles</h1>

In [10]:
def is_integer(x):
    return np.equal(np.mod(x, 1), 0)

In [11]:
numpy_is_integer = np.frompyfunc(is_integer, 1, 1)

In [12]:
number_of_triangles = 9

base = np.arange(number_of_triangles) + 1
height = np.arange(number_of_triangles) + 1

# http://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.outer.html
hypotenuse_squared = np.add.outer(base ** 2, height ** 2) 
hypotenuse = np.sqrt(hypotenuse_squared)

numpy_is_integer(hypotenuse)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, True, False, False, False, False, False],
       [False, False, True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, True, False, False, False],
       [False, False, False, False, False, False, False, False, False]], dtype=object)

# Linear Algebra

In [13]:
my_first_matrix = np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
my_first_matrix

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [14]:
# transpose
my_first_matrix.T

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [15]:
my_first_matrix.I

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [16]:
my_first_matrix * my_first_matrix.I

matrix([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   1.00000000e+00,  -1.38777878e-16],
        [  5.55111512e-17,  -1.38777878e-16,   1.00000000e+00]])

In [17]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

# Solve simultaneous Linear Equations

In [18]:
right_hand_matrix = np.matrix([ [11],
                                [22],
                                [33]])
right_hand_matrix

matrix([[11],
        [22],
        [33]])

In [19]:
my_first_inverse = my_first_matrix.I

In [20]:
my_first_inverse

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [21]:
solution = my_first_inverse * right_hand_matrix

In [22]:
solution

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])