In [1]:
import numpy as np

In [2]:
# truncated binomial: returns (x+1)**3 - (x)**3
def truncated_binomial(x):
    return (x+1)**3 - (x)**3

In [3]:
np.testing.assert_equal (truncated_binomial(4), 61)

In [4]:
np.testing.assert_equal (truncated_binomial(4), 65)

AssertionError: 
Items are not equal:
 ACTUAL: 61
 DESIRED: 65

In [5]:
my_numpy_function = np.frompyfunc(truncated_binomial, 1, 1)
my_numpy_function

<ufunc '? (vectorized)'>

In [6]:
test_array = np.arange(10)
test_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_numpy_function(test_array)

array([1, 7, 19, 37, 61, 91, 127, 169, 217, 271], dtype=object)

In [8]:
big_test_array = np.outer(test_array,test_array)
big_test_array

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [9]:
my_numpy_function(big_test_array)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 7, 19, 37, 61, 91, 127, 169, 217, 271],
       [1, 19, 61, 127, 217, 331, 469, 631, 817, 1027],
       [1, 37, 127, 271, 469, 721, 1027, 1387, 1801, 2269],
       [1, 61, 217, 469, 817, 1261, 1801, 2437, 3169, 3997],
       [1, 91, 331, 721, 1261, 1951, 2791, 3781, 4921, 6211],
       [1, 127, 469, 1027, 1801, 2791, 3997, 5419, 7057, 8911],
       [1, 169, 631, 1387, 2437, 3781, 5419, 7351, 9577, 12097],
       [1, 217, 817, 1801, 3169, 4921, 7057, 9577, 12481, 15769],
       [1, 271, 1027, 2269, 3997, 6211, 8911, 12097, 15769, 19927]], dtype=object)

<h1>Pythagorean Triangles</h1>

In [10]:
def is_integer(x):
    return np.equal(np.mod(x, 1), 0)

In [11]:
numpy_is_integer = np.frompyfunc(is_integer, 1, 1)

In [12]:
number_of_triangles = 9

base = np.arange(number_of_triangles) + 1
height = np.arange(number_of_triangles) + 1

# http://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.outer.html
hypotenuse_squared = np.add.outer(base ** 2, height ** 2) 
hypotenuse = np.sqrt(hypotenuse_squared)

numpy_is_integer(hypotenuse)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, True, False, False, False, False, False],
       [False, False, True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, True, False, False, False],
       [False, False, False, False, False, False, False, False, False]], dtype=object)

# Linear Algebra

In [13]:
my_first_matrix = np.matrix([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
my_first_matrix

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [14]:
# transpose
my_first_matrix.T

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [15]:
my_first_matrix.I

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [16]:
my_first_matrix * my_first_matrix.I

matrix([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   1.00000000e+00,  -1.38777878e-16],
        [  5.55111512e-17,  -1.38777878e-16,   1.00000000e+00]])

In [17]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

# Solve simultaneous Linear Equations

In [18]:
right_hand_matrix = np.matrix([ [11],
                                [22],
                                [33]])
right_hand_matrix

matrix([[11],
        [22],
        [33]])

In [19]:
my_first_inverse = my_first_matrix.I

In [20]:
my_first_inverse

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [21]:
solution = my_first_inverse * right_hand_matrix

In [22]:
solution

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

# Finding Pattern

In [3]:
my_teaser_array = np.array([1, 7, 19, 37, 61, 91, 127, 169, 217, 271, 331])
my_teaser_array

array([  1,   7,  19,  37,  61,  91, 127, 169, 217, 271, 331])

In [5]:
np.diff(my_teaser_array)

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [6]:
np.diff(my_teaser_array,n=2)

array([6, 6, 6, 6, 6, 6, 6, 6, 6])

In [7]:
np.diff(my_teaser_array,n=3)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
from sympy import init_session

In [ ]:
init_session()
diff(x**3)

IPython console for SymPy 1.0 (Python 3.6.3-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at http://docs.sympy.org/1.0/


In [2]:
%matplotlib inline
import scipy as sp
import numpy as np
import matplotlib.pyplot as plt

from scipy.stats import norm

In [4]:
random = np.random.rand(99)
type(random)

numpy.ndarray

In [7]:
random.mean()

0.52726572891463108

In [9]:
sp.median(random)

0.56727895669083306

In [11]:
min_max = np.array([random.min(),random.max()])
min_max

array([ 0.00487929,  0.99956052])

In [13]:
spread_measures = np.array([sp.std(random),sp.var(random)])
spread_measures

array([ 0.28580301,  0.08168336])

In [14]:
sp.stats.describe(random)

DescribeResult(nobs=99, minmax=(0.0048792946757963973, 0.9995605221236975), mean=0.52726572891463108, variance=0.082516864413018642, skewness=-0.13211464809209078, kurtosis=-1.106336611760634)

# Probability Distributions

In [15]:
iq_mean = 100
iq_std = 15
iq_distribution = norm(loc=iq_mean,scale=iq_std)
for n in np.arange(8):
    print('{:6.2f}'.format(iq_distribution.rvs()))

112.53
 86.04
107.70
121.28
116.76
159.86
101.86
103.01


In [16]:
iq_pdf = iq_distribution.pdf(110)
print('{:6.2f}'.format(iq_pdf))

  0.02


# Brain Teasers

In [17]:
np.set_printoptions(precision=2)
my_array = np.array(np.arange(10))
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
my_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [32]:
my_array = np.zeros(20)
my_array[0::5] = 4
my_array

array([ 4.,  0.,  0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  4.,  0.,  0.,
        0.,  0.,  4.,  0.,  0.,  0.,  0.])

In [34]:
matrix = np.asmatrix(np.array(np.arange(9)).reshape(3,3))
matrix

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [36]:
np.asmatrix(np.arange(9).reshape(3,3))

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [37]:
matrix.T

matrix([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [38]:
matrix = np.asmatrix(np.eye(5,dtype='int'))
matrix

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [40]:
my_bordered_array = np.ones((5,5))
my_bordered_array[1:-1,1:-1] = 0
my_bordered_array

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [41]:
my_checker_board = np.zeros((8,8),dtype=int)
my_checker_board[1::2,::2] = 1
my_checker_board[::2,1::2] = 1
print(my_checker_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [42]:
my_alternative_checker_board = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(my_alternative_checker_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [43]:
vector_size = 12
my_random_vector = np.random.random(vector_size)
my_sorted_random_vector = np.sort(my_random_vector)
print (my_sorted_random_vector)

[ 0.06  0.18  0.24  0.26  0.4   0.55  0.6   0.64  0.64  0.83  0.88  0.99]


In [44]:
camelot_dtype = [('name', 'S10'), ('height', float), ('age', int)]
camelot_values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]

In [45]:
camelot_structured_array = np.array(camelot_values, dtype=camelot_dtype)
camelot_sorted_array = np.sort(camelot_structured_array, order='height')
for n in np.arange(camelot_sorted_array.size):
    print (camelot_sorted_array[n])

(b'Galahad', 1.7, 38)
(b'Arthur', 1.8, 41)
(b'Lancelot', 1.9, 38)


In [46]:
my_ordinary_array = np.array(np.arange(12))
my_ordinary_array.flags.writeable = False
my_ordinary_array[5] = 1234

ValueError: assignment destination is read-only

In [47]:
my_3_3_array = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(my_3_3_array):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
---