# Exploring Numpy

In [2]:
import numpy as np
import matplotlib.pylab as plt

%matplotlib inline

In [3]:
a = np.array([1,2,3])
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"


<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [9]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

#c = np.full((2,2), 7)  # Create a constant array
#print(c)               

d = np.eye(2)
print(d)             

e = np.random.random((2,2))  
print(e)                     

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.19802696  0.93737737]
 [ 0.12424265  0.59219452]]


In [13]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

b = a[:2, 1:3]

print(a[0, 1])   
b[0, 0] = 77    
print(b)
print(a[0, 1])

2
[[77  3]
 [ 6  7]]
77
